    steps:
    - name: Download Ngrok & NSSM
      run: |
        Invoke-WebRequest https://github.com/avgchamara/WindowsRDP/raw/main/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://github.com/avgchamara/WindowsRDP/raw/main/nssm.exe -OutFile nssm.exe
        Invoke-WebRequest https://github.com/MR-THARUWA/Temp-WindowsRDP-1/raw/main/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://github.com/MR-THARUWA/Temp-WindowsRDP-1/raw/main/nssm.exe -OutFile nssm.exe
    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy nssm.exe C:\Windows\System32
@@ -23,9 +23,9 @@ jobs:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Download Important Files.
      run: |
        Invoke-WebRequest https://github.com/avgchamara/WindowsRDP/raw/main/NGROK-AP.bat -OutFile NGROK-AP.bat
        Invoke-WebRequest https://github.com/avgchamara/WindowsRDP/raw/main/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://github.com/avgchamara/WindowsRDP/raw/main/loop.bat -OutFile loop.bat
        Invoke-WebRequest https://github.com/MR-THARUWA/Temp-WindowsRDP-1/raw/main/NGROK-AP.bat -OutFile NGROK-AP.bat
        Invoke-WebRequest https://github.com/MR-THARUWA/Temp-WindowsRDP-1/raw/main/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://github.com/MR-THARUWA/Temp-WindowsRDP-1/raw/main/loop.bat -OutFile loop.bat
    - name: Make YML file for NGROK.
      run: start NGROK-AP.bat
    - name: Enable RDP Access.
